//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VDABMovies.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Film
    {
        public Film()
        {
            this.VerhuurCollectie = new HashSet<Verhuur>();
        }
    
        public int BandNr { get; set; }
        public string Titel { get; set; }
        public int GenreNr { get; set; }
        public int InVoorraad { get; set; }
        public int UitVoorraad { get; set; }
        public decimal Prijs { get; set; }
        public int TotaalVerhuurd { get; set; }
    
        public virtual ICollection<Verhuur> VerhuurCollectie { get; set; }
        public virtual Genre Genre { get; set; }
    }
}
